10/11/18 11:06:23 PM - D:/Documentos/Python/POO_Python/POO_Python_Udemy/Seção 4/usando_log/aula.py - INFO - Mensagem informativa
10/11/18 11:06:23 PM - D:/Documentos/Python/POO_Python/POO_Python_Udemy/Seção 4/usando_log/aula.py - ERROR - Um erro aconteceu
